### ISSUE TITLE
build error: dev.js:6

### ISSUE THREAD

**Issue by TedLyngmo** [RossMcMillan92/djent#1]
Excellent project! :+1: 

I'm getting a build errors on FC23, nodejs.x86_64 0.10.42-4.fc23 though:

```
% node dev.js build

/home/ted/public_html/djent/dev.js:6
const [ node, entryFile, task ] = process.argv;
      ^
SyntaxError: Unexpected token [
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

```
And for tests too:
```
% node tests.js

/home/ted/public_html/djent/tests.js:13
const startTests = (testSource, filename) => {
                                           ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

```

Br,
Ted

**Comment by RossMcMillan92** [comment]
Try running it on node 6.2.0. It looks like the error is because I'm using es6 syntax which node <6 doesn't support.
